COLUMNS:
     CustomerID: "int64"
     Churn: "int64"
     Tenure: "float64"
     PreferredLoginDevice : "object"
     CityTier: "int64"  
     WarehouseToHome: "float64"
     PreferredPaymentMode: "object"
     Gender: "object"
     HourSpendOnApp: "float64"
     NumberOfDeviceRegistered: "int64"
     PreferedOrderCat: "object"
     SatisfactionScore: "int64"  
     MaritalStatus: "object" 
     NumberOfAddress: "int64" 
     Complain: "int64"  
     OrderAmountHikeFromlastYear: "float64"
     CouponUsed: "float64"
     OrderCount: "float64"
     DaySinceLastOrder: "float64"
     CashbackAmount: "float64"
     source: "object"
     data_last_updated_dt: "object"
TARGET_COLUMNS:
     Churn: "int64"